INSERT INTO book VALUES 
	('Pro', 'Proverbs', 'OT');
  
INSERT INTO testament VALUES 
	('OT', 'Old Testament'),
	('NT', 'New Testament');
  
INSERT INTO verse VALUES 
	('Pro', '001', '001', 'The proverbs of Solomon the son of David, king of Israel;'),
	('Pro', '001', '002', 'To know wisdom and instruction; to perceive the words of understanding;'),
	('Pro', '001', '003', 'To receive the instruction of wisdom, justice, and judgment, and equity;'),
	('Pro', '001', '004', 'To give subtilty to the simple, to the young man knowledge and discretion.'),
	('Pro', '001', '005', 'A wise man will hear, and will increase learning; and a man of understanding shall attain unto wise counsels:'),
	('Pro', '001', '006', 'To understand a proverb, and the interpretation; the words of the wise, and their dark sayings.'),
	('Pro', '001', '007', 'The fear of the Lord is the beginning of knowledge: but fools despise wisdom and instruction.'),
	('Pro', '001', '008', 'My son, hear the instruction of thy father, and forsake not the law of thy mother:'),
	('Pro', '001', '009', 'For they shall be an ornament of grace unto thy head, and chains about thy neck.'),
	('Pro', '001', '010', 'My son, if sinners entice thee, consent thou not.'),
	('Pro', '001', '011', 'If they say, Come with us, let us lay wait for blood, let us lurk privily for the innocent without cause:'),
	('Pro', '001', '012', 'Let us swallow them up alive as the grave; and whole, as those that go down into the pit:'),
	('Pro', '001', '013', 'We shall find all precious substance, we shall fill our houses with spoil:'),
	('Pro', '001', '014', 'Cast in thy lot among us; let us all have one purse:'),
	('Pro', '001', '015', 'My son, walk not thou in the way with them; refrain thy foot from their path:'),
	('Pro', '001', '016', 'For their feet run to evil, and make haste to shed blood.'),
	('Pro', '001', '017', 'Surely in vain the net is spread in the sight of any bird.'),
	('Pro', '001', '018', 'And they lay wait for their own blood; they lurk privily for their own lives.'),
	('Pro', '001', '019', 'So are the ways of every one that is greedy of gain; which taketh away the life of the owners thereof.'),
	('Pro', '001', '020', 'Wisdom crieth without; she uttereth her voice in the streets:'),
	('Pro', '001', '021', 'She crieth in the chief place of concourse, in the openings of the gates: in the city she uttereth her words, saying,'),
	('Pro', '001', '022', 'How long, ye simple ones, will ye love simplicity? and the scorners delight in their scorning, and fools hate knowledge?'),
	('Pro', '001', '023', 'Turn you at my reproof: behold, I will pour out my spirit unto you, I will make known my words unto you.'),
	('Pro', '001', '024', 'Because I have called, and ye refused; I have stretched out my hand, and no man regarded;'),
	('Pro', '001', '025', 'But ye have set at nought all my counsel, and would none of my reproof:'),
	('Pro', '001', '026', 'I also will laugh at your calamity; I will mock when your fear cometh;'),
	('Pro', '001', '027', 'When your fear cometh as desolation, and your destruction cometh as a whirlwind; when distress and anguish cometh upon you.'),
	('Pro', '001', '028', 'Then shall they call upon me, but I will not answer; they shall seek me early, but they shall not find me:'),
	('Pro', '001', '029', 'For that they hated knowledge, and did not choose the fear of the Lord:'),
	('Pro', '001', '030', 'They would none of my counsel: they despised all my reproof.'),
	('Pro', '001', '031', 'Therefore shall they eat of the fruit of their own way, and be filled with their own devices.'),
	('Pro', '001', '032', 'For the turning away of the simple shall slay them, and the prosperity of fools shall destroy them.'),
	('Pro', '001', '033', 'But whoso hearkeneth unto me shall dwell safely, and shall be quiet from fear of evil.')
	('Pro', '002', '001', 'My son, if thou wilt receive my words, and hide my commandments with thee;'),
	('Pro', '002', '002', 'So that thou incline thine ear unto wisdom, and apply thine heart to understanding;'),
	('Pro', '002', '003', 'Yea, if thou criest after knowledge, and liftest up thy voice for understanding;'),
	('Pro', '002', '004', 'If thou seekest her as silver, and searchest for her as for hid treasures;'),
	('Pro', '002', '005', 'Then shalt thou understand the fear of the Lord, and find the knowledge of God.'),
	('Pro', '002', '006', 'For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding.'),
	('Pro', '002', '007', 'He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly.'),
	('Pro', '002', '008', 'He keepeth the paths of judgment, and preserveth the way of his saints.'),
	('Pro', '002', '009', 'Then shalt thou understand righteousness, and judgment, and equity; yea, every good path.'),
	('Pro', '002', '010', 'When wisdom entereth into thine heart, and knowledge is pleasant unto thy soul;'),
	('Pro', '002', '011', 'Discretion shall preserve thee, understanding shall keep thee:'),
	('Pro', '002', '012', 'To deliver thee from the way of the evil man, from the man that speaketh froward things;'),
	('Pro', '002', '013', 'Who leave the paths of uprightness, to walk in the ways of darkness;'),
	('Pro', '002', '014', 'Who rejoice to do evil, and delight in the frowardness of the wicked;'),
	('Pro', '002', '015', 'Whose ways are crooked, and they froward in their paths:'),
	('Pro', '002', '016', 'To deliver thee from the strange woman, even from the stranger which flattereth with her words;'),
	('Pro', '002', '017', 'Which forsaketh the guide of her youth, and forgetteth the covenant of her God.'),
	('Pro', '002', '018', 'For her house inclineth unto death, and her paths unto the dead.'),
	('Pro', '002', '019', 'None that go unto her return again, neither take they hold of the paths of life.'),
	('Pro', '002', '020', 'That thou mayest walk in the way of good men, and keep the paths of the righteous.'),
	('Pro', '002', '021', 'For the upright shall dwell in the land, and the perfect shall remain in it.'),
	('Pro', '002', '022', 'But the wicked shall be cut off from the earth, and the transgressors shall be rooted out of it.')
	('Pro', '003', '001', 'My son, forget not my law; but let thine heart keep my commandments:'),
	('Pro', '003', '002', 'For length of days, and long life, and peace, shall they add to thee.'),
	('Pro', '003', '003', 'Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:'),
	('Pro', '003', '004', 'So shalt thou find favour and good understanding in the sight of God and man.'),
	('Pro', '003', '005', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.'),
	('Pro', '003', '006', 'In all thy ways acknowledge him, and he shall direct thy paths.'),
	('Pro', '003', '007', 'Be not wise in thine own eyes: fear the Lord, and depart from evil.'),
	('Pro', '003', '008', 'It shall be health to thy navel, and marrow to thy bones.'),
	('Pro', '003', '009', 'Honour the Lord with thy substance, and with the firstfruits of all thine increase:'),
	('Pro', '003', '010', 'So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.'),
	('Pro', '003', '011', 'My son, despise not the chastening of the Lord; neither be weary of his correction:'),
	('Pro', '003', '012', 'For whom the Lord loveth he correcteth; even as a father the son in whom he delighteth.'),
	('Pro', '003', '013', 'Happy is the man that findeth wisdom, and the man that getteth understanding.'),
	('Pro', '003', '014', 'For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold.'),
	('Pro', '003', '015', 'She is more precious than rubies: and all the things thou canst desire are not to be compared unto her.'),
	('Pro', '003', '016', 'Length of days is in her right hand; and in her left hand riches and honour.'),
	('Pro', '003', '017', 'Her ways are ways of pleasantness, and all her paths are peace.'),
	('Pro', '003', '018', 'She is a tree of life to them that lay hold upon her: and happy is every one that retaineth her.'),
	('Pro', '003', '019', 'The Lord by wisdom hath founded the earth; by understanding hath he established the heavens.'),
	('Pro', '003', '020', 'By his knowledge the depths are broken up, and the clouds drop down the dew.'),
	('Pro', '003', '021', 'My son, let not them depart from thine eyes: keep sound wisdom and discretion:'),
	('Pro', '003', '022', 'So shall they be life unto thy soul, and grace to thy neck.'),
	('Pro', '003', '023', 'Then shalt thou walk in thy way safely, and thy foot shall not stumble.'),
	('Pro', '003', '024', 'When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet.'),
	('Pro', '003', '025', 'Be not afraid of sudden fear, neither of the desolation of the wicked, when it cometh.'),
	('Pro', '003', '026', 'For the Lord shall be thy confidence, and shall keep thy foot from being taken.'),
	('Pro', '003', '027', 'Withhold not good from them to whom it is due, when it is in the power of thine hand to do it.'),
	('Pro', '003', '028', 'Say not unto thy neighbour, Go, and come again, and to morrow I will give; when thou hast it by thee.'),
	('Pro', '003', '029', 'Devise not evil against thy neighbour, seeing he dwelleth securely by thee.'),
	('Pro', '003', '030', 'Strive not with a man without cause, if he have done thee no harm.'),
	('Pro', '003', '031', 'Envy thou not the oppressor, and choose none of his ways.'),
	('Pro', '003', '032', 'For the froward is abomination to the Lord: but his secret is with the righteous.'),
	('Pro', '003', '033', 'The curse of the Lord is in the house of the wicked: but he blesseth the habitation of the just.'),
	('Pro', '003', '034', 'Surely he scorneth the scorners: but he giveth grace unto the lowly.'),
	('Pro', '003', '035', 'The wise shall inherit glory: but shame shall be the promotion of fools.')
	('Pro', '004', '001', 'Hear, ye children, the instruction of a father, and attend to know understanding.'),
	('Pro', '004', '002', 'For I give you good doctrine, forsake ye not my law.'),
	('Pro', '004', '003', 'For I was my father\'s son, tender and only beloved in the sight of my mother.'),
	('Pro', '004', '004', 'He taught me also, and said unto me, Let thine heart retain my words: keep my commandments, and live.'),
	('Pro', '004', '005', 'Get wisdom, get understanding: forget it not; neither decline from the words of my mouth.'),
	('Pro', '004', '007', 'Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.'),
	('Pro', '004', '008', 'Exalt her, and she shall promote thee: she shall bring thee to honour, when thou dost embrace her.'),
	('Pro', '004', '009', 'She shall give to thine head an ornament of grace: a crown of glory shall she deliver to thee.'),
	('Pro', '004', '010', 'Hear, O my son, and receive my sayings; and the years of thy life shall be many.'),
	('Pro', '004', '011', 'I have taught thee in the way of wisdom; I have led thee in right paths.'),
	('Pro', '004', '012', 'When thou goest, thy steps shall not be straitened; and when thou runnest, thou shalt not stumble.'),
	('Pro', '004', '013', 'Take fast hold of instruction; let her not go: keep her; for she is thy life.'),
	('Pro', '004', '014', 'Enter not into the path of the wicked, and go not in the way of evil men.'),
	('Pro', '004', '015', 'Avoid it, pass not by it, turn from it, and pass away.'),
	('Pro', '004', '016', 'For they sleep not, except they have done mischief; and their sleep is taken away, unless they cause some to fall.'),
	('Pro', '004', '017', 'For they eat the bread of wickedness, and drink the wine of violence.'),
	('Pro', '004', '018', 'But the path of the just is as the shining light, that shineth more and more unto the perfect day.'),
	('Pro', '004', '019', 'The way of the wicked is as darkness: they know not at what they stumble.'),
	('Pro', '004', '020', 'My son, attend to my words; incline thine ear unto my sayings.'),
	('Pro', '004', '021', 'Let them not depart from thine eyes; keep them in the midst of thine heart.'),
	('Pro', '004', '022', 'For they are life unto those that find them, and health to all their flesh.'),
	('Pro', '004', '023', 'Keep thy heart with all diligence; for out of it are the issues of life.'),
	('Pro', '004', '024', 'Put away from thee a froward mouth, and perverse lips put far from thee.'),
	('Pro', '004', '025', 'Let thine eyes look right on, and let thine eyelids look straight before thee.'),
	('Pro', '004', '026', 'Ponder the path of thy feet, and let all thy ways be established.'),
	('Pro', '004', '027', 'Turn not to the right hand nor to the left: remove thy foot from evil.')
	('Pro', '005', '001', 'My son, attend unto my wisdom, and bow thine ear to my understanding:'),
	('Pro', '005', '002', 'That thou mayest regard discretion, and that thy lips may keep knowledge.'),
	('Pro', '005', '003', 'For the lips of a strange woman drop as an honeycomb, and her mouth is smoother than oil:'),
	('Pro', '005', '004', 'But her end is bitter as wormwood, sharp as a two-edged sword.'),
	('Pro', '005', '005', 'Her feet go down to death; her steps take hold on hell.'),
	('Pro', '005', '006', 'Lest thou shouldest ponder the path of life, her ways are moveable, that thou canst not know them.'),
	('Pro', '005', '007', 'Hear me now therefore, O ye children, and depart not from the words of my mouth.'),
	('Pro', '005', '008', 'Remove thy way far from her, and come not nigh the door of her house:'),
	('Pro', '005', '009', 'Lest thou give thine honour unto others, and thy years unto the cruel:'),
	('Pro', '005', '010', 'Lest strangers be filled with thy wealth; and thy labours be in the house of a stranger;'),
	('Pro', '005', '011', 'And thou mourn at the last, when thy flesh and thy body are consumed,'),
	('Pro', '005', '012', 'And say, How have I hated instruction, and my heart despised reproof;'),
	('Pro', '005', '013', 'And have not obeyed the voice of my teachers, nor inclined mine ear to them that instructed me!'),
	('Pro', '005', '014', 'I was almost in all evil in the midst of the congregation and assembly.'),
	('Pro', '005', '015', 'Drink waters out of thine own cistern, and running waters out of thine own well.'),
	('Pro', '005', '016', 'Let thy fountains be dispersed abroad, and rivers of waters in the streets.'),
	('Pro', '005', '017', 'Let them be only thine own, and not strangers\' with thee.'),
	('Pro', '005', '018', 'Let thy fountain be blessed: and rejoice with the wife of thy youth.'),
	('Pro', '005', '019', 'Let her be as the loving hind and pleasant roe; let her breasts satisfy thee at all times; and be thou ravished always with her love.'),
	('Pro', '005', '020', 'And why wilt thou, my son, be ravished with a strange woman, and embrace the bosom of a stranger?'),
	('Pro', '005', '021', 'For the ways of man are before the eyes of the Lord, and he pondereth all his goings.'),
	('Pro', '005', '022', 'His own iniquities shall take the wicked himself, and he shall be holden with the cords of his sins.'),
	('Pro', '005', '023', 'He shall die without instruction; and in the greatness of his folly he shall go astray.')
	('Pro', '006', '001', 'My son, if thou be surety for thy friend, if thou hast stricken thy hand with a stranger,'),
	('Pro', '006', '002', 'Thou art snared with the words of thy mouth, thou art taken with the words of thy mouth.'),
	('Pro', '006', '003', 'Do this now, my son, and deliver thyself, when thou art come into the hand of thy friend; go, humble thyself, and make sure thy friend.'),
	('Pro', '006', '004', 'Give not sleep to thine eyes, nor slumber to thine eyelids.'),
	('Pro', '006', '005', 'Deliver thyself as a roe from the hand of the hunter, and as a bird from the hand of the fowler.'),
	('Pro', '006', '006', 'Go to the ant, thou sluggard; consider her ways, and be wise:'),
	('Pro', '006', '007', 'Which having no guide, overseer, or ruler,'),
	('Pro', '006', '008', 'Provideth her meat in the summer, and gathereth her food in the harvest.'),
	('Pro', '006', '009', 'How long wilt thou sleep, O sluggard? when wilt thou arise out of thy sleep?'),
	('Pro', '006', '010', 'Yet a little sleep, a little slumber, a little folding of the hands to sleep:'),
	('Pro', '006', '011', 'So shall thy poverty come as one that travelleth, and thy want as an armed man.'),
	('Pro', '006', '012', 'A naughty person, a wicked man, walketh with a froward mouth.'),
	('Pro', '006', '013', 'He winketh with his eyes, he speaketh with his feet, he teacheth with his fingers;'),
	('Pro', '006', '014', 'Frowardness is in his heart, he deviseth mischief continually; he soweth discord.'),
	('Pro', '006', '015', 'Therefore shall his calamity come suddenly; suddenly shall he be broken without remedy.'),
	('Pro', '006', '016', 'These six things doth the Lord hate: yea, seven are an abomination unto him:'),
	('Pro', '006', '017', 'A proud look, a lying tongue, and hands that shed innocent blood,'),
	('Pro', '006', '018', 'An heart that deviseth wicked imaginations, feet that be swift in running to mischief,'),
	('Pro', '006', '019', 'A false witness that speaketh lies, and he that soweth discord among brethren.'),
	('Pro', '006', '020', 'My son, keep thy father\'s commandment, and forsake not the law of thy mother:'),
	('Pro', '006', '021', 'Bind them continually upon thine heart, and tie them about thy neck.'),
	('Pro', '006', '022', 'When thou goest, it shall lead thee; when thou sleepest, it shall keep thee; and when thou awakest, it shall talk with thee.'),
	('Pro', '006', '023', 'For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life:'),
	('Pro', '006', '024', 'To keep thee from the evil woman, from the flattery of the tongue of a strange woman.'),
	('Pro', '006', '025', 'Lust not after her beauty in thine heart; neither let her take thee with her eyelids.'),
	('Pro', '006', '026', 'For by means of a whorish woman a man is brought to a piece of bread: and the adultress will hunt for the precious life.'),
	('Pro', '006', '027', 'Can a man take fire in his bosom, and his clothes not be burned?'),
	('Pro', '006', '028', 'Can one go upon hot coals, and his feet not be burned?'),
	('Pro', '006', '029', 'So he that goeth in to his neighbour\'s wife; whosoever toucheth her shall not be innocent.'),
	('Pro', '006', '030', 'Men do not despise a thief, if he steal to satisfy his soul when he is hungry;'),
	('Pro', '006', '031', 'But if he be found, he shall restore sevenfold; he shall give all the substance of his house.'),
	('Pro', '006', '032', 'But whoso committeth adultery with a woman lacketh understanding: he that doeth it destroyeth his own soul.'),
	('Pro', '006', '033', 'A wound and dishonour shall he get; and his reproach shall not be wiped away.'),
	('Pro', '006', '034', 'For jealousy is the rage of a man: therefore he will not spare in the day of vengeance.'),
	('Pro', '006', '035', 'He will not regard any ransom; neither will he rest content, though thou givest many gifts.')
	('Pro', '007', '001', 'My son, keep my words, and lay up my commandments with thee.'),
	('Pro', '007', '002', 'Keep my commandments, and live; and my law as the apple of thine eye.'),
	('Pro', '007', '003', 'Bind them upon thy fingers, write them upon the table of thine heart.'),
	('Pro', '007', '004', 'Say unto wisdom, Thou art my sister; and call understanding thy kinswoman:'),
	('Pro', '007', '005', 'That they may keep thee from the strange woman, from the stranger which flattereth with her words.'),
	('Pro', '007', '006', 'For at the window of my house I looked through my casement,'),
	('Pro', '007', '007', 'And beheld among the simple ones, I discerned among the youths, a young man void of understanding,'),
	('Pro', '007', '008', 'Passing through the street near her corner; and he went the way to her house,'),
	('Pro', '007', '009', 'In the twilight, in the evening, in the black and dark night:'),
	('Pro', '007', '010', 'And, behold, there met him a woman with the attire of an harlot, and subtil of heart.'),
	('Pro', '007', '011', '(She is loud and stubborn; her feet abide not in her house:'),
	('Pro', '007', '012', 'Now is she without, now in the streets, and lieth in wait at every corner.)'),
	('Pro', '007', '013', 'So she caught him, and kissed him, and with an impudent face said unto him,'),
	('Pro', '007', '014', 'I have peace offerings with me; this day have I payed my vows.'),
	('Pro', '007', '015', 'Therefore came I forth to meet thee, diligently to seek thy face, and I have found thee.'),
	('Pro', '007', '016', 'I have decked my bed with coverings of tapestry, with carved works, with fine linen of Egypt.'),
	('Pro', '007', '017', 'I have perfumed my bed with myrrh, aloes, and cinnamon.'),
	('Pro', '007', '018', 'Come, let us take our fill of love until the morning: let us solace ourselves with loves.'),
	('Pro', '007', '019', 'For the goodman is not at home, he is gone a long journey:'),
	('Pro', '007', '020', 'He hath taken a bag of money with him, and will come home at the day appointed.'),
	('Pro', '007', '021', 'With her much fair speech she caused him to yield, with the flattering of her lips she forced him.'),
	('Pro', '007', '022', 'He goeth after her straightway, as an ox goeth to the slaughter, or as a fool to the correction of the stocks;'),
	('Pro', '007', '023', 'Till a dart strike through his liver; as a bird hasteth to the snare, and knoweth not that it is for his life.'),
	('Pro', '007', '024', 'Hearken unto me now therefore, O ye children, and attend to the words of my mouth.'),
	('Pro', '007', '025', 'Let not thine heart decline to her ways, go not astray in her paths.'),
	('Pro', '007', '026', 'For she hath cast down many wounded: yea, many strong men have been slain by her.'),
	('Pro', '007', '027', 'Her house is the way to hell, going down to the chambers of death.')
	('Pro', '008', '001', 'Doth not wisdom cry? and understanding put forth her voice?'),
	('Pro', '008', '002', 'She standeth in the top of high places, by the way in the places of the paths.'),
	('Pro', '008', '003', 'She crieth at the gates, at the entry of the city, at the coming in at the doors.'),
	('Pro', '008', '004', 'Unto you, O men, I call; and my voice is to the sons of man.'),
	('Pro', '008', '005', 'O ye simple, understand wisdom: and, ye fools, be ye of an understanding heart.'),
	('Pro', '008', '006', 'Hear; for I will speak of excellent things; and the opening of my lips shall be right things.'),
	('Pro', '008', '007', 'For my mouth shall speak truth; and wickedness is an abomination to my lips.'),
	('Pro', '008', '008', 'All the words of my mouth are in righteousness; there is nothing froward or perverse in them.'),
	('Pro', '008', '009', 'They are all plain to him that understandeth, and right to them that find knowledge.'),
	('Pro', '008', '010', 'Receive my instruction, and not silver; and knowledge rather than choice gold.'),
	('Pro', '008', '011', 'For wisdom is better than rubies; and all the things that may be desired are not to be compared to it.'),
	('Pro', '008', '012', 'I wisdom dwell with prudence, and find out knowledge of witty inventions.'),
	('Pro', '008', '013', 'The fear of the Lord is to hate evil: pride, and arrogancy, and the evil way, and the froward mouth, do I hate.'),
	('Pro', '008', '014', 'Counsel is mine, and sound wisdom: I am understanding; I have strength.'),
	('Pro', '008', '015', 'By me kings reign, and princes decree justice.'),
	('Pro', '008', '016', 'By me princes rule, and nobles, even all the judges of the earth.'),
	('Pro', '008', '017', 'I love them that love me; and those that seek me early shall find me.'),
	('Pro', '008', '018', 'Riches and honour are with me; yea, durable riches and righteousness.'),
	('Pro', '008', '019', 'My fruit is better than gold, yea, than fine gold; and my revenue than choice silver.'),
	('Pro', '008', '020', 'I lead in the way of righteousness, in the midst of the paths of judgment:'),
	('Pro', '008', '021', 'That I may cause those that love me to inherit substance; and I will fill their treasures.'),
	('Pro', '008', '022', 'The Lord possessed me in the beginning of his way, before his works of old.'),
	('Pro', '008', '023', 'I was set up from everlasting, from the beginning, or ever the earth was.'),
	('Pro', '008', '024', 'When there were no depths, I was brought forth; when there were no fountains abounding with water.'),
	('Pro', '008', '025', 'Before the mountains were settled, before the hills was I brought forth:'),
	('Pro', '008', '026', 'While as yet he had not made the earth, nor the fields, nor the highest part of the dust of the world.'),
	('Pro', '008', '027', 'When he prepared the heavens, I was there: when he set a compass upon the face of the depth:'),
	('Pro', '008', '028', 'When he established the clouds above: when he strengthened the fountains of the deep:'),
	('Pro', '008', '029', 'When he gave to the sea his decree, that the waters should not pass his commandment: when he appointed the foundations of the earth:'),
	('Pro', '008', '030', 'Then I was by him, as one brought up with him: and I was daily his delight, rejoicing always before him;'),
	('Pro', '008', '031', 'Rejoicing in the habitable part of his earth; and my delights were with the sons of men.'),
	('Pro', '008', '032', 'Now therefore hearken unto me, O ye children: for blessed are they that keep my ways.'),
	('Pro', '008', '033', 'Hear instruction, and be wise, and refuse it not.'),
	('Pro', '008', '034', 'Blessed is the man that heareth me, watching daily at my gates, waiting at the posts of my doors.'),
	('Pro', '008', '035', 'For whoso findeth me findeth life, and shall obtain favour of the Lord.'),
	('Pro', '008', '036', 'But he that sinneth against me wrongeth his own soul: all they that hate me love death.')
	('Pro', '009', '001', 'Wisdom hath builded her house, she hath hewn out her seven pillars:'),
	('Pro', '009', '002', 'She hath killed her beasts; she hath mingled her wine; she hath also furnished her table.'),
	('Pro', '009', '003', 'She hath sent forth her maidens: she crieth upon the highest places of the city,'),
	('Pro', '009', '004', 'Whoso is simple, let him turn in hither: as for him that wanteth understanding, she saith to him,'),
	('Pro', '009', '005', 'Come, eat of my bread, and drink of the wine which I have mingled.'),
	('Pro', '009', '006', 'Forsake the foolish, and live; and go in the way of understanding.'),
	('Pro', '009', '007', 'He that reproveth a scorner getteth to himself shame: and he that rebuketh a wicked man getteth himself a blot.'),
	('Pro', '009', '008', 'Reprove not a scorner, lest he hate thee: rebuke a wise man, and he will love thee.'),
	('Pro', '009', '009', 'Give instruction to a wise man, and he will be yet wiser: teach a just man, and he will increase in learning.'),
	('Pro', '009', '010', 'The fear of the Lord is the beginning of wisdom: and the knowledge of the holy is understanding.'),
	('Pro', '009', '011', 'For by me thy days shall be multiplied, and the years of thy life shall be increased.'),
	('Pro', '009', '012', 'If thou be wise, thou shalt be wise for thyself: but if thou scornest, thou alone shalt bear it.'),
	('Pro', '009', '013', 'A foolish woman is clamorous: she is simple, and knoweth nothing.'),
	('Pro', '009', '014', 'For she sitteth at the door of her house, on a seat in the high places of the city,'),
	('Pro', '009', '015', 'To call passengers who go right on their ways:'),
	('Pro', '009', '016', 'Whoso is simple, let him turn in hither: and as for him that wanteth understanding, she saith to him,'),
	('Pro', '009', '017', 'Stolen waters are sweet, and bread eaten in secret is pleasant.'),
	('Pro', '009', '018', 'But he knoweth not that the dead are there; and that her guests are in the depths of hell.')
	('Pro', '010', '001', '^The proverbs of Solomon. A wise son maketh a glad father: but a foolish son is the heaviness of his mother.'),
	('Pro', '010', '002', 'Treasures of wickedness profit nothing: but righteousness delivereth from death.'),
	('Pro', '010', '003', 'The Lord will not suffer the soul of the righteous to famish: but he casteth away the substance of the wicked.'),
	('Pro', '010', '004', 'He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich.'),
	('Pro', '010', '005', 'He that gathereth in summer is a wise son: but he that sleepeth in harvest is a son that causeth shame.'),
	('Pro', '010', '006', 'Blessings are upon the head of the just: but violence covereth the mouth of the wicked.'),
	('Pro', '010', '007', 'The memory of the just is blessed: but the name of the wicked shall rot.'),
	('Pro', '010', '008', 'The wise in heart will receive commandments: but a prating fool shall fall.'),
	('Pro', '010', '009', 'He that walketh uprightly walketh surely: but he that perverteth his ways shall be known.'),
	('Pro', '010', '010', 'He that winketh with the eye causeth sorrow: but a prating fool shall fall.'),
	('Pro', '010', '011', 'The mouth of a righteous man is a well of life: but violence covereth the mouth of the wicked.'),
	('Pro', '010', '012', 'Hatred stirreth up strifes: but love covereth all sins.'),
	('Pro', '010', '013', 'In the lips of him that hath understanding wisdom is found: but a rod is for the back of him that is void of understanding.'),
	('Pro', '010', '014', 'Wise men lay up knowledge: but the mouth of the foolish is near destruction.'),
	('Pro', '010', '015', 'The rich man\'s wealth is his strong city: the destruction of the poor is their poverty.'),
	('Pro', '010', '016', 'The labour of the righteous tendeth to life: the fruit of the wicked to sin.'),
	('Pro', '010', '017', 'He is in the way of life that keepeth instruction: but he that refuseth reproof erreth.'),
	('Pro', '010', '018', 'He that hideth hatred with lying lips, and he that uttereth a slander, is a fool.'),
	('Pro', '010', '019', 'In the multitude of words there wanteth not sin: but he that refraineth his lips is wise.'),
	('Pro', '010', '020', 'The tongue of the just is as choice silver: the heart of the wicked is little worth.'),
	('Pro', '010', '021', 'The lips of the righteous feed many: but fools die for want of wisdom.'),
	('Pro', '010', '022', 'The blessing of the Lord, it maketh rich, and he addeth no sorrow with it.'),
	('Pro', '010', '023', 'It is as sport to a fool to do mischief: but a man of understanding hath wisdom.'),
	('Pro', '010', '024', 'The fear of the wicked, it shall come upon him: but the desire of the righteous shall be granted.'),
	('Pro', '010', '025', 'As the whirlwind passeth, so is the wicked no more: but the righteous is an everlasting foundation.'),
	('Pro', '010', '026', 'As vinegar to the teeth, and as smoke to the eyes, so is the sluggard to them that send him.'),
	('Pro', '010', '027', 'The fear of the Lord prolongeth days: but the years of the wicked shall be shortened.'),
	('Pro', '010', '028', 'The hope of the righteous shall be gladness: but the expectation of the wicked shall perish.'),
	('Pro', '010', '029', 'The way of the Lord is strength to the upright: but destruction shall be to the workers of iniquity.'),
	('Pro', '010', '030', 'The righteous shall never be removed: but the wicked shall not inhabit the earth.'),
	('Pro', '010', '031', 'The mouth of the just bringeth forth wisdom: but the froward tongue shall be cut out.'),
	('Pro', '010', '032', 'The lips of the righteous know what is acceptable: but the mouth of the wicked speaketh frowardness.')
	('Pro', '011', '001', 'A false balance is abomination to the Lord: but a just weight is his delight.'),
	('Pro', '011', '002', 'When pride cometh, then cometh shame: but with the lowly is wisdom.'),
	('Pro', '011', '003', 'The integrity of the upright shall guide them: but the perverseness of transgressors shall destroy them.'),
	('Pro', '011', '004', 'Riches profit not in the day of wrath: but righteousness delivereth from death.'),
	('Pro', '011', '005', 'The righteousness of the perfect shall direct his way: but the wicked shall fall by his own wickedness.'),
	('Pro', '011', '006', 'The righteousness of the upright shall deliver them: but transgressors shall be taken in their own naughtiness.'),
	('Pro', '011', '007', 'When a wicked man dieth, his expectation shall perish: and the hope of unjust men perisheth.'),
	('Pro', '011', '008', 'The righteous is delivered out of trouble, and the wicked cometh in his stead.'),
	('Pro', '011', '009', 'An hypocrite with his mouth destroyeth his neighbour: but through knowledge shall the just be delivered.'),
	('Pro', '011', '010', 'When it goeth well with the righteous, the city rejoiceth: and when the wicked perish, there is shouting.'),
	('Pro', '011', '011', 'By the blessing of the upright the city is exalted: but it is overthrown by the mouth of the wicked.'),
	('Pro', '011', '012', 'He that is void of wisdom despiseth his neighbour: but a man of understanding holdeth his peace.'),
	('Pro', '011', '013', 'A talebearer revealeth secrets: but he that is of a faithful spirit concealeth the matter.'),
	('Pro', '011', '014', 'Where no counsel is, the people fall: but in the multitude of counsellors there is safety.'),
	('Pro', '011', '015', 'He that is surety for a stranger shall smart for it: and he that hateth suretiship is sure.'),
	('Pro', '011', '016', 'A gracious woman retaineth honour: and strong men retain riches.'),
	('Pro', '011', '017', 'The merciful man doeth good to his own soul: but he that is cruel troubleth his own flesh.'),
	('Pro', '011', '018', 'The wicked worketh a deceitful work: but to him that soweth righteousness shall be a sure reward.'),
	('Pro', '011', '019', 'As righteousness tendeth to life: so he that pursueth evil pursueth it to his own death.'),
	('Pro', '011', '020', 'They that are of a froward heart are abomination to the Lord: but such as are upright in their way are his delight.'),
	('Pro', '011', '021', 'Though hand join in hand, the wicked shall not be unpunished: but the seed of the righteous shall be delivered.'),
	('Pro', '011', '022', 'As a jewel of gold in a swine\'s snout, so is a fair woman which is without discretion.'),
	('Pro', '011', '023', 'The desire of the righteous is only good: but the expectation of the wicked is wrath.'),
	('Pro', '011', '024', 'There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty.'),
	('Pro', '011', '025', 'The liberal soul shall be made fat: and he that watereth shall be watered also himself.'),
	('Pro', '011', '026', 'He that withholdeth corn, the people shall curse him: but blessing shall be upon the head of him that selleth it.'),
	('Pro', '011', '027', 'He that diligently seeketh good procureth favour: but he that seeketh mischief, it shall come unto him.'),
	('Pro', '011', '028', 'He that trusteth in his riches shall fall; but the righteous shall flourish as a branch.'),
	('Pro', '011', '029', 'He that troubleth his own house shall inherit the wind: and the fool shall be servant to the wise of heart.'),
	('Pro', '011', '030', 'The fruit of the righteous is a tree of life; and he that winneth souls is wise.'),
	('Pro', '011', '031', 'Behold, the righteous shall be recompensed in the earth: much more the wicked and the sinner.');
